name: Foxy Ladies Running Club
favicon: null
layout_spectrum: 0.34093
typography_spectrum: 0.05145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#eb6706'
    - '#1c1c1b'
    - '#92470f'
    - '#f19047'
  brandStrength: 0.7663089993875474
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
